### PR TITLE
Fixes

### LINKED ISSUE #171: When starting a new game, selecting the flags or the character can sometimes wipe other information that you put in
When starting a new game, selecting the flags to customize your personal or pirate flag or the character to choose your own character can sometimes wipe other information that you put in like the name of the save profile or custom ship names that you put in. This may be a bit more of an engine bug, idk, but I think this should be fully fixed in the final version that way we knock out even the smaller, more annoying bugs!

Still happening as of Alpha 21, also happens in build 14 as far as I'm aware.

### PR DESCRIPTION
**Pull request by LipsarJ**
profilename was resetting after other changes. fixes #171

### CODE REVIEW

**Comment by Hammie** [comment]
Also fixes #139 and #178

File: PROGRAM/INTERFACE/kam_generalfunctions.c [hunk 1]
```diff
@@ -32,8 +32,6 @@ string KAM_GetDefaultEmblemedSail(ref char)
 		case 4: // Pure White, with emblems
 			tempstring = "sail_purewhite_nation" + char.nation + ".tga";
 		break;
-		// default, with emblems
```
Comment (Hammie) [inline PROGRAM/INTERFACE/kam_generalfunctions.c:35]: Any reason why we deleted these default cases? Or just because they should never happen?

**Review by Hammie — APPROVED** [review]
